name:                patch-splitter
version:             0.1.0.0
github:              "flaviusb/patch-splitter"
license:             GPL-3
author:              "Justin (:flaviusb) Marsh"
maintainer:          "justin.marsh@flaviusb.net"
copyright:           "2018 Justin (:flaviusb) Marsh"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Application

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/flaviusb/patch-splitter#readme>

dependencies:
- base >= 4.7 && < 5
- peggy
- text >=0.11 && <2.0
- optparse-applicative

library:
  source-dirs: src

executables:
  patch-splitter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - patch-splitter

tests:
  patch-splitter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - patch-splitter
